/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const EditorVideoIdLazyImport = createFileRoute('/editor/$videoId')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const EditorVideoIdLazyRoute = EditorVideoIdLazyImport.update({
  path: '/editor/$videoId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/editor.$videoId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/editor/$videoId': {
      id: '/editor/$videoId'
      path: '/editor/$videoId'
      fullPath: '/editor/$videoId'
      preLoaderRoute: typeof EditorVideoIdLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/editor/$videoId': typeof EditorVideoIdLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/editor/$videoId': typeof EditorVideoIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/editor/$videoId': typeof EditorVideoIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/editor/$videoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/editor/$videoId'
  id: '__root__' | '/' | '/editor/$videoId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  EditorVideoIdLazyRoute: typeof EditorVideoIdLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  EditorVideoIdLazyRoute: EditorVideoIdLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/editor/$videoId"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/editor/$videoId": {
      "filePath": "editor.$videoId.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
